#!/usr/bin/env python3

"""Main driver wrapper around the manic/checkout utility.

Tool to assemble external respositories represented in an externals
description file.

"""

import sys
import traceback

import manic

if sys.hexversion < 0x03060000:
    print(70 * '*')
    print(f'ERROR: {sys.argv[0]} requires python >= 3.6.x. ')
    version = '.'.join(str(x) for x in sys.version_info[0:3])
    print(f'It appears that you are running python {version}')
    print(70 * '*')
    sys.exit(1)


if __name__ == '__main__':
    ARGS = manic.checkout.commandline_arguments()
    try:
        RET_STATUS, _ = manic.checkout.main(ARGS)
        sys.exit(RET_STATUS)
    except Exception as error:  # pylint: disable=broad-except
        manic.printlog(str(error))
        if ARGS.backtrace:
            traceback.print_exc()
        sys.exit(1)
